import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextUIProvider } from '@nextui-org/react';
import { ConfigProvider, Button } from "antd";
import './globals.scss'; // Ensure you have a SCSS file for global styles
import 'antd/dist/reset.css'; // Import Ant Design styles
// src/index.tsx or src/App.tsx
// import 'antd/dist/antd.less';




const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
		<html lang="en">
			<body className={inter.className}>
				<NextUIProvider>
					<ConfigProvider theme={{ token: { colorPrimary: "#FBFF30" } }}>{children}</ConfigProvider>
				</NextUIProvider>
			</body>
		</html>
	);
}
